### PR TITLE
Compatibility with Symfony >=2.7

### PR DESCRIPTION
**Pull request by fabdsp**
SecurityContext is now deprecated, replaced by TokenStorage.

A new major version.

http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements

### CODE REVIEW

**Comment by mikaelrandy** [comment]
:+1:

**Comment by fabdsp** [comment]
@adriensamson ?

**Comment by mojoLyon** [comment]
:+1: 

Major release

**Comment by adriensamson** [comment]
:+1:

**Comment by fabdsp** [comment]
v2.0.0

**Pull request merged**
